Create procfile
Nurutomo/wabot-aq pull request #1023
Opened 2022-01-23 17:14 UTC by DIMASZBOT

2022-02-01 12:00 UTC, aditya12311 requested changes
worker : npm i ffmpeg && npm i @adiwajshing/baileys@latest

2022-02-01 12:24 UTC, Nikesyg commented
Ada lagi nih anak hamdehh

2022-02-04 08:08 UTC, Nurhidayat2619 commented
> worker : npm i ffmpeg && npm i @adiwajshing/baileys@latest

Kan bisa ditambahin buildpack :)

2022-02-04 12:16 UTC, Nikesyg commented
Hamdehh gini nih kalo pertama kali pasang bot :v

2022-02-10 01:00 UTC, closed without merging