Add Fitur Report/Bug
Nurutomo/wabot-aq pull request #125
Opened 2021-03-17 07:35 UTC by RC047

Kalo ada masalah pada fitur/ada yang erorr bisa dilaporin keowner lewat fitur ini :)

2021-03-18 09:57 UTC, M-Mahmudd commented
chat wa.me/6289662518213 gw ada fitur lapor bug

2021-03-21 02:54 UTC, Nurutomo commented
Itu nomor siapa njir :v
kenapa nggk pake list owner

2021-03-21 06:56 UTC, RC047 commented
sama lu aja sempurnain :v

2021-03-21 13:48 UTC, Nurutomo commented
jangan nomorku

2021-03-21 14:06 UTC, RC047 commented
> 
> 
> jangan nomorku

Lahh terus no siapa? di global.owner kan nomormu

2021-03-22 00:15 UTC, Arya274 commented
Ubah nomor 0@s.whatsapp.net kayak yg di creator.js

2021-03-22 00:43 UTC, RC047 commented
> Ubah nomor [0@s.whatsapp.net](mailto:0@s.whatsapp.net) kayak yg di creator.js

Ntar kebannedlah,, kan ngirim pesan ke owner wa??

2021-03-22 00:43 UTC, RC047 commented
Kebanned salahin lu aja ya:v

2021-03-22 07:23 UTC, Nurutomo requested changes
Ubah jadi ini aja maksudku

2021-03-22 07:23 UTC, Nurutomo commented on plugins/report.js
> +    await conn.reply('6281111111111@s.whatsapp.net', laporan, m)
```js
for (let jid of global.owner.map(v => v.replace(/[^0-9]/g, '') + '@s.whatsapp.net').filter(v => v != conn.user.jid))
  m.reply(laporan, jid)
```

2021-03-22 07:59 UTC, RC047 commented on plugins/report.js
> +    await conn.reply('6281111111111@s.whatsapp.net', laporan, m)
:v

2021-03-22 10:59 UTC, merged