Create siapakah.js
Nurutomo/wabot-aq pull request #165
Opened 2021-03-30 01:22 UTC by Nobuyaki

2021-03-30 03:05 UTC, RC047 commented
Colong ahh :v

2021-03-30 03:27 UTC, Nobuyaki commented
> Colong ahh :v

Silahkan Bang :v

2021-03-30 03:35 UTC, Nurutomo requested changes
ganti dikit :v

2021-03-30 03:35 UTC, Nurutomo commented on plugins/siapakah.js
> +    let member = (await conn.groupMetadata(m.chat)).participants.map(u => u.jid)
dapetin participants bisa ambil argumen....

```js
let handler = async (m, { conn, text, participants }) => {
  let member = participants.map(u => u.jid)
}
```

2021-04-26 03:58 UTC, Nurutomo commented
uhh

2021-04-26 03:58 UTC, closed without merging