Create stickfilter.js
Nurutomo/wabot-aq pull request #272
Opened 2021-05-14 04:05 UTC by anshuljai

🙃

2021-05-14 06:12 UTC, lilnext01 commented
![Screenshot_20210514-031226_GBWhatsApp](https://user-images.githubusercontent.com/74841546/118229371-43124e80-b462-11eb-886b-9533da4c14ba.jpg)
Why

2021-05-15 03:05 UTC, Nurutomo requested changes

2021-05-15 03:05 UTC, Nurutomo commented on stickfilter.js
> +  await m.reply(global.wait)
same as #271

2021-05-16 09:29 UTC, RC047 commented
global.wait = 'Wait in progress...'

2021-06-01 07:04 UTC, closed without merging