[ Feature ] List Premium
Nurutomo/wabot-aq pull request #276
Opened 2021-05-15 12:44 UTC by Miaweers

2021-05-17 12:45 UTC, anshuljai commented
idiot

2021-05-17 14:47 UTC, KazukoGans commented
> idiot

Lah?

2021-05-17 21:34 UTC, Miaweers commented
Aneh ( ಠ_ಠ)

2021-05-19 00:12 UTC, Ftwrr commented
> idiot
 Lah?

2021-05-19 14:12 UTC, Nurutomo requested changes
tolong diubah dikit ya;v

2021-05-19 14:12 UTC, Nurutomo commented on plugins/setbotpp.js
> +handler.rowner = true
```js
handler.owner = true
```

aja, kasihan yang jadibot gabisa setpp

2021-05-19 21:15 UTC, Miaweers reviewed
Ok

2021-05-19 21:26 UTC, Miaweers commented
> tolong diubah dikit ya

Ke delete repo patch-1 nya 😂

2021-05-19 21:30 UTC, closed without merging