Create nulis2.js
Nurutomo/wabot-aq pull request #78
Opened 2021-02-26 03:42 UTC by MFarelS

2021-02-27 11:52 UTC, Nurutomo requested changes
Typo :v

2021-02-27 11:52 UTC, Nurutomo commented on plugins/nulis2.js
> +handler.command = /^nulis$2/i
No:
```js
/^nulis$2/i
```

Yes:
```js
/^nulis2$/i
```

2021-03-07 06:47 UTC, lilnext01 commented
Tambahkan opsi rotasi

2021-04-19 02:30 UTC, MFarelS commented
done om

2021-05-01 06:06 UTC, Nurutomo commented
Wkwkwkwk

2021-05-01 06:06 UTC, merged