Add Banned user
Nurutomo/wabot-aq pull request #94
Opened 2021-03-07 01:24 UTC by BochilGaming

:)

2021-03-11 08:49 UTC, Nurutomo requested changes
Ok, tpi ada sedikit kesalahan...
jadi tidak bisa ban

2021-03-11 08:49 UTC, Nurutomo commented on handler.js
> +            if (name != 'unbanchat.js' && chat && chat.isBanned && name != 'unbanuser.js' && user && user.banned) return // Except this
Itu jangan dijadiin satu, dipisah aja

2021-03-11 09:17 UTC, BochilGaming commented on handler.js
> +            if (name != 'unbanchat.js' && chat && chat.isBanned && name != 'unbanuser.js' && user && user.banned) return // Except this
Maksutnya yang dipisisah apanya? Hehe `:)

2021-03-11 09:22 UTC, BochilGaming reviewed
Kayak itu kah?

2021-03-12 03:14 UTC, Nurutomo commented on handler.js
> +            if (name != 'unbanchat.js' && chat && chat.isBanned && name != 'unbanuser.js' && user && user.banned) return // Except this
If nya

2021-03-12 03:17 UTC, merged